close all
clear
clc

dataset = "stats";
dataout = dataset + "_c";

dinfo = dir(fullfile(dataset));
dinfo([dinfo.isdir]) = [];
nfiles = length(dinfo);

nparts = 2; %the number of parts generated by python
i0 = 1;
cut = 11; %remove some chars from the name

fbase = dinfo(i0).name;
n = length(fbase);
filename = fullfile(dataset, fbase);
tdata = load(filename);
pbase = fbase(1:n-cut);
parts = 1;

for i = i0+1 : nfiles
  fbase = dinfo(i).name;
  n = length(fbase);
  filename = fullfile(dataset, fbase);
  data = load(filename);

  if strcmp(pbase, fbase(1:n-cut))
      tdata = [tdata, data];
      parts = parts + 1;
  else
      if parts < nparts
          fprintf('%s has only %d parts!\n', pbase, parts)
      else
          fprintf('i=%d, processed %s\n', i-1, pbase)
      end
      filename = fullfile(dataout, [pbase, '.csv']);
      writematrix(tdata,filename);
      tdata = data;
      pbase = fbase(1:n-cut);
      parts = 1;
  end
end
